name: AutoDock Vina Docking

on:
  push:
    branches:
      - main  # Puedes cambiarlo para que se ejecute en otro evento, como un 'pull_request'

jobs:
  run_docking:
    runs-on: ubuntu-latest  # Usa un runner hospedado en GitHub con Ubuntu

    steps:
      # 1. Checkout del repositorio para que el código esté disponible
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Descargar y configurar AutoDock Vina desde el código fuente
      - name: Download and compile AutoDock Vina
        run: |
          # Instalar dependencias necesarias
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git
          
          # Clonar el repositorio de AutoDock Vina
          git clone https://github.com/ccsb-scripps/AutoDock-Vina.git
          cd AutoDock-Vina

          # Crear directorios de compilación y compilar el código fuente
          mkdir build
          cd build
          cmake ..
          make

      # 3. Configurar permisos para el archivo ejecutable
      - name: Set executable permissions for vina
        run: chmod +x ./AutoDock-Vina/build/vina  # Si estás en Linux, se usará el ejecutable de Linux

      # 4. Ejecutar AutoDock Vina
      - name: Execute AutoDock Vina
        run: ./AutoDock-Vina/build/vina --help  # Ejecuta el comando que necesites
